dist: xenial
sudo: enabled

language: python
python:
  - "3.6"
  - "3.7"

cache: pip
addons:
  apt:
    packages:
    - gcc
    - psmisc
    - pkg-config
    - libattr1-dev
    - libsqlite3-dev
    - libjs-sphinxdoc
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-generic-extra
    - texlive-fonts-recommended
    - python3-pip
    - python3-setuptools
    - ninja-build

install: tests/travis-install.sh

script:
  - python setup.py build_cython || travis_terminate 1
  - python setup.py build_ext --inplace || travis_terminate 1
  - (coverage run -m pytest tests && coveralls ) || travis_terminate 1
  - python setup.py build_sphinx || travis_terminate 1
  - python setup.py install
