name: "build"

on: 
  push:
    tags-ignore:
      - "release-*"
  pull_request_review:
  workflow_dispatch:
  workflow_call:
    outputs:
      aname:
        value: ${{jobs.build.outputs.aname}}
      version:
        value: ${{jobs.build.outputs.version}}
        

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      aname: ${{ steps.aname.outputs.artifactname }}
      version: ${{ steps.getversion.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - id: getversion
      shell: python
      run: |
        import os,sys,subprocess,site

        if not subprocess.call([sys.executable, '-m', 'pip', 'install','build']):
          sys.path.append(site.USER_SITE)
          
          import build.util
          
          with open(os.environ["GITHUB_OUTPUT"], "a+") as fout:
            fout.write("version={}".format(build.util.project_wheel_metadata(srcdir=".")["Version"]))
        else:
          sys.exit(1)
    - id: build
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu
        options: -v ${{ github.workspace }}:/work
        shell: bash
        run: |
          apt update
          apt -y install python3-pip python3-venv libsqlite3-dev pkg-config libfuse3-dev
          pip3 install build
          cd /work
          python3 -m build
          pip3 install dist/s3ql-${{ steps.getversion.outputs.version }}.whl
          pip wheel -w ./dist -r requirements.txt
          python3 -c 'import s3ql; print("prevver={}".format(s3ql.REV_VER_MAP[s3ql.CURRENT_FS_REV-1]))' > ./dist/prev-version
    - id: test
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu
        options: -v ${{ github.workspace }}:/work --device=/dev/fuse --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
        run: |
          apt update
          apt -y install --no-install-recommends libsqlite3-0 libfuse3-3 python3-pip rsync fuse psmisc curl
          pip install --find-links /work/dist s3ql
          tar zxf /work/dist/s3ql-${{ steps.getversion.outputs.version }}.tar.gz
          cd s3ql-${{ steps.getversion.outputs.version }}
          rm -rf src
          prevver=$(cat /work/dist/prev-version)
          curl -sL https://github.com/s3ql/s3ql/releases/download/release-${prevver}/s3ql-${prevver}.tar.gz | tar ztf -
          mv s3ql-${prevver} s3ql.old
          cd s3ql.old
          python3 setup.py build_ext --inplace
          cd ..
          pip install pytest_trio
          pytest tests
    - id: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.sha}}
        path: ${{github.workspace}}/dist/s3ql-${{ steps.getversion.outputs.version }}.tar.gz
        if-no-files-found: error
    - id: aname
      run: echo "artifactname=${{github.sha}}" >> ${GITHUB_OUTPUT}
