name: "build"

on:
  push:
    tags:
      - "!release-*"
    branches:
      - "*"
  pull_request_review:
  workflow_dispatch:
  workflow_call:
    outputs:
      aname:
        value: ${{jobs.build.outputs.aname}}
      version:
        value: ${{jobs.build.outputs.version}}


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      aname: ${{ steps.aname.outputs.artifactname }}
      version: ${{ steps.getversion.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - id: getversion
      shell: python
      run: |
        import os,sys,subprocess,site

        if not subprocess.call([sys.executable, '-m', 'pip', 'install','build']):
          sys.path.append(site.USER_SITE)

          import build.util

          with open(os.environ["GITHUB_OUTPUT"], "a+") as fout:
            fout.write("version={}".format(build.util.project_wheel_metadata(source_dir=".")["Version"]))
        else:
          sys.exit(1)
    - id: build
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu
        options: -v ${{ github.workspace }}:/work --device=/dev/fuse --cap-add=SYS_ADMIN --security-opt apparmor:unconfined
        shell: bash
        run: |
          apt update
          apt -y install python3-pip python3-venv libsqlite3-dev pkg-config libfuse3-dev rsync fuse psmisc curl
          python3 -m venv /s3ql-venv --system-site-packages
          source /s3ql-venv/bin/activate
          pip3 install --ignore-installed build pip setuptools pytest_trio
          cd /work
          python3 -m build
          pip3 install dist/s3ql-${{ steps.getversion.outputs.version }}-*.whl
          pip3 wheel -w ./dist -r requirements.txt
          prevver=$(python3 -c 'import s3ql; print("{}".format(s3ql.REV_VER_MAP[s3ql.CURRENT_FS_REV-1]))')
          rm -rf src
          if curl -sL https://github.com/s3ql/s3ql/releases/download/release-${prevver}/s3ql-${prevver}.tar.gz | tar zxf -;
          then
            mv s3ql-${prevver} s3ql.old
            cd s3ql.old
            pip3 install cython dugong
            python3 setup.py build_cython
            python3 setup.py build_ext --inplace
            cd ..
          fi
          pytest tests
    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.sha}}
        path: ${{github.workspace}}/dist/s3ql-${{ steps.getversion.outputs.version }}.tar.gz
        if-no-files-found: error
    - id: aname
      run: echo "artifactname=${{github.sha}}" >> ${GITHUB_OUTPUT}
