name: "tagged-release"

on: 
  push:
    tags:
    - "release-*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.aname }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: s3ql-${{needs.build.outputs.version}}.tar.gz
