name: "tagged-release"

on: 
  push:
    tags:
    - "release-*"
    - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/s3ql-*.tar.gz"
